### ISSUE TITLE
Shelly RGBW2 firmware problem/limit/incompatible

### ISSUE THREAD

**Issue by acrobat88** [chaptergy/lightalarm-card#27]
Shelly RGBW2 devices allow only 5sec transition time - its a firmware limit. Is there a workaround for the transition?

**Comment by chaptergy** [comment]
This lightalarm card is only a frontend thing, it does not have any logic. I offer some information about how I did it in the readme, but it is not universal. So unfurtunately if your device does not support you'll have to create a transition in home assistant then. Probably using an automation, updating the state every 5 seconds, or what ever your transition time is. But I can't tell you much more, as I have never done something like that either.
